services:
  mumbot-irc:
    container_name: "mumbot-irc"
    image: theta142/hubot-docker:latest
    restart: "on-failure"
    
    # For debugging
    # command: "./debug_entry.sh"
    # ports:
    #   - 9229:9229
    
    environment:
      HUBOT_NAME: hubot
      HUBOT_IRC_NICK: hubot
      EXTERNAL_SCRIPTS: true
      EXTRA_PACKAGES: true
      REDIS_URL: redis://hubotbrain:6379
      HUBOT_ADAPTER: "@hubot-friends/hubot-irc"
      HUBOT_IRC_SERVER: your_irc_server.com
      HUBOT_IRC_PORT: 6697
      HUBOT_IRC_ROOMS: "#main"
      HUBOT_IRC_UNFLOOD: true
      HUBOT_IRC_PASSWORD: totallysecret
      HUBOT_LOG_LEVEL: debug
      HUBOT_IRC_REALNAME: Benevolent Robot Overlord
      # HUBOT_IRC_USESSL: true
      
    volumes:
      # Scripts and packages
      - "./extra-packages.json:/home/hubot/hubot/extra-packages.json:ro"
      - "./external-scripts.json:/home/hubot/hubot/external-scripts.json:ro"
      - "./scripts:/home/hubot/hubot/scripts:ro"
      # For debugging
      # - "./debug_entry.sh:/home/hubot/hubot/debug_entry.sh:ro"
      # - "./node_modules:/home/hubot/hubot/node_modules"
      
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    
  hubotbrain:
    container_name: hubotbrain
    command:
      - --save 60 1
    restart: always
    volumes:
      - redis_data:/data
    environment:
      - PGID=1000
      - PUID=1000
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
        
  volumes:
    redis_data:
      external: false
version: "3.7"